Add exercise convertidor de temperatura
Laboratoria/preseleccion-labs pull request #4
Opened 2021-03-11 22:26 UTC by moniyama

Please, check my Spanish

2021-03-18 20:00 UTC, luucamay commented on 03-guided-exercises/02-convertidor-de-temperatura/README.md
> +- Crear la estructura de nuestra página web dentro de nuestro de `index.html`.
Borrar la palabra **de** porque está demás
```suggestion
- Crear la estructura de nuestra página web dentro de nuestro `index.html`.
```

2021-03-18 20:06 UTC, luucamay requested changes
Solo corregir un par de detalles dejados en general

2021-03-18 20:06 UTC, luucamay commented on 03-guided-exercises/02-convertidor-de-temperatura/README.md
> +Pone el `prompt` dentro del metodo `parseInt()` en la variable `temperaturaCelsius`:
Un pequeño detalle de español! Pero en general lo vi muy 🔝
```suggestion
Pon el `prompt` dentro del metodo `parseInt()` en la variable `temperaturaCelsius`:
```

2021-03-19 17:01 UTC, merunga approved these changes

2021-03-19 17:02 UTC, merunga commented
@moniyama ya incluí los comentarios @luucamay

2021-03-19 17:25 UTC, merged