readme ejercicio 04
Laboratoria/preseleccion-labs pull request #6
Opened 2021-03-16 18:55 UTC by moniyama

2021-03-19 17:09 UTC, merunga approved these changes

2021-03-19 17:09 UTC, merunga commented on 03-guided-exercises/04-iniciales/README.md
> +Crea un programa que pide el nombre y apellido al usuario. El
```suggestion
Crea un programa que pida al usuario un nombre y apellido a la usuaria,
y devuelva las iniciales **en mayúsculas**.

La usuaria debe ingresar dos palabras separadas por un espacio, por ejemplo:
"Ana Martinez".

Veamos unos ejemplos:
- "ana martinez" y "Ana Martinez" devuelven las iniciales "AM".
- "Michelle Seguil" y "michelle seguil" devuelven "MS"
```

2021-03-19 17:09 UTC, merunga commented on 03-guided-exercises/04-iniciales/README.md
> +Las iniciales ya aparecen en la pantalla.. pero puedo testear que cuando escribimos
```suggestion
Las iniciales ya aparecen en la pantalla... pero puedo testear que cuando escribimos
```

2021-03-19 17:10 UTC, merunga commented on 03-guided-exercises/04-iniciales/README.md
> +Crea un programa que pide el nombre y apellido al usuario. El
@luucamay debje una propuesta de cómo hacer que el enunciado sea mas claro.
Me parece que ayuda a que la definición de input y output estén en una misma oración.
que opinan?

2021-03-29 20:37 UTC, merunga requested changes

2021-03-29 20:37 UTC, merunga commented on 03-guided-exercises/04-iniciales/README.md
> +Crea un programa que pide el nombre y apellido al usuario. El
@moniyama chequea esto porfa para ver si te hace sentido. @luucamay

2021-04-05 18:23 UTC, moniyama commented on 03-guided-exercises/04-iniciales/README.md
> +Crea un programa que pide el nombre y apellido al usuario. El
ahhh sí @merunga!!  Me parece bueníssimo! Voy a cambiar!

2021-04-09 17:09 UTC, merunga requested changes
buenisimo @moniyama 
son principalmente temas de traducción

2021-04-09 17:09 UTC, merunga commented on 03-guided-exercises/04-iniciales/README.md
> +Solo con el é `slice()` no es possible obtener la segunda inicial,
```suggestion
Solo con `slice()` no es posible obtener la segunda inicial,
```

2021-04-09 17:09 UTC, merunga commented on 03-guided-exercises/04-iniciales/README.md
> +por qué su posición no es fixa...
```suggestion
porque su posición no es fija...
```

2021-04-09 17:09 UTC, merunga commented on 03-guided-exercises/04-iniciales/README.md
> +Por ejemplo, para el nombre "Ana Martinez", la segunda inicial es la posición 4,
```suggestion
Por ejemplo, para el nombre "Ana Martinez", la segunda inicial está en la posición 4,
```

2021-04-09 17:09 UTC, merunga commented on 03-guided-exercises/04-iniciales/README.md
> +pero para "Michelle Seguil" es la posición 9.
```suggestion
pero para "Michelle Seguil" está en la posición 9.
```

2021-04-09 17:09 UTC, merunga commented on 03-guided-exercises/04-iniciales/README.md
> +Vamos a:
```suggestion
Veamos:
```

2021-04-09 17:09 UTC, merunga commented on 03-guided-exercises/04-iniciales/README.md
> +Así, vamos encuentrar la posición del espacio primero, pois sabemos que
```suggestion
Entonces, primero vamos a encontrar la posición del espacio, ya que sabemos que
```

2021-04-09 17:09 UTC, merunga commented on 03-guided-exercises/04-iniciales/README.md
> +la posición de la segunda inicial es la seguiente.
```suggestion
la posición de la segunda inicial es la siguiente.
```

2021-04-09 17:09 UTC, merunga commented on 03-guided-exercises/04-iniciales/README.md
> +Vamos utilizar el método `indexOf()` que toma un argumento y sirve para encuentrar
```suggestion
Vamos utilizar el método `indexOf()` que toma un argumento y sirve para encontrar
```

2021-04-09 17:09 UTC, merunga commented on 03-guided-exercises/04-iniciales/README.md
> +la posición del argumento dentro de la _string_. La posición es llamada de `index`.
```suggestion
la posición del argumento dentro del _string_. Esa posición es llamada `index`.
```

2021-04-09 17:09 UTC, merunga commented on 03-guided-exercises/04-iniciales/README.md
> +//"Ana Martinez!" es la string dónde vamos a procurar la posición del argumento
```suggestion
//"Ana Martinez!" es el `string` dónde vamos a buscar la posición del argumento
```

2021-04-09 17:09 UTC, merunga commented on 03-guided-exercises/04-iniciales/README.md
> +Testea en su consola el método y cambia el argumento como quiera:
```suggestion
Testea en su consola el método y cambia el argumento:
```

2021-04-09 17:09 UTC, merunga commented on 03-guided-exercises/04-iniciales/README.md
> +Testea en su consola el método y cambia el argumento como quiera:
aca @moniyama no entiendo para que es el "como quiera", qué quieres decir?

2021-04-09 17:09 UTC, merunga commented on 03-guided-exercises/04-iniciales/README.md
> +// el argumento es el caractere " " (espacio)
```suggestion
// el argumento es el carácter " " (espacio)
```

2021-04-09 17:09 UTC, merunga commented on 03-guided-exercises/04-iniciales/README.md
> +¿Como podemos hacer, entonces?
```suggestion
¿Cómo podemos hacer entonces?
```

2021-04-09 17:09 UTC, merunga commented on 03-guided-exercises/04-iniciales/README.md
> +ATENCIÓN: La posición 0 es la *primera* letra de la _string_.
```suggestion
ATENCIÓN: La *primera* letra del _string_ está en la posición 0,
```

2021-04-09 17:09 UTC, merunga commented on 03-guided-exercises/04-iniciales/README.md
> +La posición  1, es la segunda letra y así sucesivamente.
```suggestion
la *segunda* letra en la posición 1, y así sucesivamente
```

2021-04-09 17:09 UTC, merunga commented on 03-guided-exercises/04-iniciales/README.md
> +La posición de la segunda inicial es la seguiente del espacio, portanto es:
```suggestion
La posición de la segunda inicial es la que le sigue al espacio, por tanto:
```

2021-04-09 17:09 UTC, merunga commented on 03-guided-exercises/04-iniciales/README.md
> +Como queremos hacer esto con el nombre del prompt,
```suggestion
Como queremos hacer esto con el nombre obtenido a través de `window.prompt`,
```

2021-04-09 17:09 UTC, merunga commented on 03-guided-exercises/04-iniciales/README.md
> +vamos a usar el é slice novamente..
```suggestion
vamos a usar `slice` nuevamente..
```

2021-04-09 17:09 UTC, merunga commented on 03-guided-exercises/04-iniciales/README.md
> +terminando un caractere después:
```suggestion
terminando un carácter después:
```

2021-04-09 17:09 UTC, merunga commented on 03-guided-exercises/04-iniciales/README.md
> +un nombre como "ana martinez", las iniciales deberiam ser "AM" y no "am".
```suggestion
un nombre como "ana martinez" (todo en minúsculas), las iniciales deberiam ser "AM" y no "am".
```

2021-04-09 17:09 UTC, merunga commented on 03-guided-exercises/04-iniciales/README.md
> +en las dos letreas iniciales
```suggestion
en cada una de las iniciales
```

2021-04-09 17:09 UTC, merunga commented on 03-guided-exercises/04-iniciales/README.md
> +y retorna toda la _string_ en mayúsculas.
```suggestion
y retorna todo el _string_ en mayúsculas.
```

2021-04-09 17:09 UTC, merunga commented on 03-guided-exercises/04-iniciales/README.md
> +Una condición común es que la primera letra del apellido es después del espacio.
```suggestion
Una condición común es que la primera letra del apellido está inmediatamente después del espacio.
```

2021-04-09 17:09 UTC, merunga commented on 03-guided-exercises/04-iniciales/README.md
> +const nombre = prompt('¿Cuál es tu nombre y apellido?');
```suggestion
const nombre = window.prompt('¿Cuál es tu nombre y apellido?');
```

2021-04-09 17:09 UTC, merunga commented on 03-guided-exercises/04-iniciales/README.md
> +Deve aparecer el valor ingresado en el _prompt_.
```suggestion
Debe aparecer el valor ingresado en el _prompt_.
```

2021-04-09 17:09 UTC, merunga commented on 03-guided-exercises/04-iniciales/README.md
> +En la consola, escriba la variable `nombre` y presione `enter`.
```suggestion
En la consola, escribe la variable `nombre` y presiona `enter`.
```

2021-04-09 17:09 UTC, merunga commented on 03-guided-exercises/04-iniciales/README.md
> +El método `slice()` toma dos argumentos y sirve para cortar la `string`.
```suggestion
El método `slice()` toma dos argumentos y sirve para cortar una "porción" del `string`.
```

2021-04-09 17:09 UTC, merunga commented on 03-guided-exercises/04-iniciales/README.md
> +El primero es donde vas a comenzar a cortar y el segundo donde vas a terminar.
```suggestion
El primer argumento indica en qué posición del `string` vas a comenzar a cortar y el segundo dónde vas a terminar.
```

2021-04-09 17:09 UTC, merunga commented on 03-guided-exercises/04-iniciales/README.md
> +ATENCIÓN: La posición 0 es la *primera* letra de la _string_.
```suggestion
ATENCIÓN: La *primera* letra del _string_ está en la posición 0,
```

2021-04-09 17:09 UTC, merunga commented on 03-guided-exercises/04-iniciales/README.md
> +La posición  1, es la segunda letra y así sucesivamente.
```suggestion
la *segunda* letra en la posición 1, y así sucesivamente
```

2021-04-12 12:32 UTC, moniyama commented
@merunga listo!

2021-04-15 03:45 UTC, luucamay approved these changes

2021-04-15 03:45 UTC, merged