Prework exercises: coinConverter y restaurantBill
Laboratoria/preseleccion-labs pull request #7
Opened 2021-03-18 19:37 UTC by luucamay

2021-03-19 17:24 UTC, merunga requested changes

2021-03-19 17:24 UTC, merunga commented on 05-prework-exercises/01-coin-convert/README.md
> +TO DO: PREGUNTAR SI DEBERIA PEDIR ESTE DATO CON UN PROMPT DE NUEVO Y LUEGO IMPRIMIR EN PANTALLA EL RESULTADO?
@luucamay aquí quedamos que fuera solo `js`

2021-03-19 17:24 UTC, merunga commented on 05-prework-exercises/01-coin-convert/README.md
> +- Abrir el archivo `coinConvert.js` que tiene una _función flecha_ llamada `coinConvert`
```suggestion
- Abrir el archivo `coinConvert.js` que tiene una _función_ llamada `coinConvert`
```

2021-03-19 17:24 UTC, merunga commented on 05-prework-exercises/01-coin-convert/README.md
> +  - `pesosChilenos`
Para hacerlo mas inclusivo, les parece que agreguemos _reales_ y _pesos colombianos_?

2021-03-19 17:24 UTC, merunga commented on 05-prework-exercises/01-coin-convert/README.md
> +```text
hay que actualizar estas cotizaciones
el sol ya está 3.65

2021-03-19 17:24 UTC, merunga commented on 05-prework-exercises/01-coin-convert/README.md
> +### Calculo del valor de la variable `pesosChilenos`
a partir de aquí yo no volvería a poner código, sino que pondría algo así como
> repite el proceso para `pesosChilenos`

2021-03-19 17:24 UTC, merunga commented on 05-prework-exercises/01-coin-convert/package.json
> +    "chai": "^4.3.4",
`jest`

2021-03-19 17:24 UTC, merunga commented on 05-prework-exercises/01-coin-convert/src/coinConvert.js
> +const coinConvert = (dolares) => {
convertir en `function`

2021-03-19 17:24 UTC, merunga commented on 05-prework-exercises/01-coin-convert/src/coinConvert.js
> +  const soles = /* ??? */;
este codigo como esta ahora, a la primera falla porque la sintaxis esta mal, les parece q los inicialicemos con `undefined` o `0`?

2021-03-19 17:24 UTC, merunga commented on 05-prework-exercises/01-coin-convert/src/coinConvert.js
> +  const soles = /* ??? */;
lo mismo para el resto de los valores

2021-03-19 17:24 UTC, merunga commented on 05-prework-exercises/01-coin-convert/test/coinConvert.spec.js
> +    const soles = dollars * 3.25;
extraer las contantes del tipo de cambio fuera de los tests, por ejemplo
```js
const CAMBIO_SOLES = 3.65;
const CAMBIO_PESOS_CHILENOS = 600;
...
```

2021-03-19 17:24 UTC, merunga commented on 05-prework-exercises/02-restaurant-bill/README.md
> +## Abre el archivo `coinConvert.js`
```suggestion
## Abre el archivo `restaurantBill.js`
```

2021-03-19 17:24 UTC, merunga commented on 05-prework-exercises/02-restaurant-bill/README.md
> +Asigna el resultado de multiplicar `cuenta` por `0.1` en la variable `impuesto`. Nota: `10%` en decimal se escribe `0.1`.
A ver que les parece algo menos mágico:
Calculemos el 10% de `cuenta` con una regla de 3, y coloquemos el valor en una nueva variable `impuesto`
```js
const impuesto = (cuenta * 10) / 100; // generalmente escribirías esto como cuenta * 0.1
```

2021-03-19 17:24 UTC, merunga commented on 05-prework-exercises/02-restaurant-bill/README.md
> +- Abrir el archivo `restaurantBill.js` que tiene una _función flecha_ llamada `restaurantBill`
```suggestion
- Abrir el archivo `restaurantBill.js` que tiene una _función_ llamada `restaurantBill`
```

2021-03-19 17:24 UTC, merunga commented on 05-prework-exercises/02-restaurant-bill/src/restaurantBill.js
> +const restaurantBill = (cuenta) => {
que les parece si la cantidad de amigas tb es un parametro
```suggestion
const restaurantBill = (cuenta, cantDeAmigas) => {
```

2021-03-19 17:24 UTC, merunga commented on 05-prework-exercises/02-restaurant-bill/src/restaurantBill.js
> +  const impuesto = /* ??? */
lo mismo q con el anterior, inicializaria estas variables, no se que opinan

2021-03-19 17:24 UTC, merunga commented on 05-prework-exercises/02-restaurant-bill/test/restaurantBill.spec.js
> +    const tax = preTaxAmount * 0.1;
extraer el % de impuesto a una constante

2021-03-19 17:24 UTC, merunga commented on 05-prework-exercises/02-restaurant-bill/README.md
> +## Estructura de la función `restaurantBill`
@luucamay esto estaba en el original? no se si tiene sentido aqui al final, me parece q puede funcionar mejor al comienzo

2021-03-19 17:24 UTC, merunga commented on 05-prework-exercises/01-coin-convert/README.md
> +## Estructura de la función `coinConvert`
@luucamay esto estaba en el original? no se si tiene sentido aqui al final, me parece q puede funcionar mejor al comienzo

2021-04-15 19:25 UTC, luucamay commented on 05-prework-exercises/01-coin-convert/README.md
> +```text
listo

2021-04-15 19:45 UTC, luucamay commented on 05-prework-exercises/01-coin-convert/README.md
> +  - `pesosChilenos`
listo!

2021-04-15 19:45 UTC, luucamay commented on 05-prework-exercises/01-coin-convert/README.md
> +### Calculo del valor de la variable `pesosChilenos`
hecho

2021-04-15 20:10 UTC, luucamay commented on 05-prework-exercises/02-restaurant-bill/test/restaurantBill.spec.js
> +    const tax = preTaxAmount * 0.1;
no entiendo este comentario

2021-04-15 20:31 UTC, luucamay commented on 05-prework-exercises/02-restaurant-bill/src/restaurantBill.js
> +  const impuesto = /* ??? */
listo

2021-04-15 20:31 UTC, luucamay commented on 05-prework-exercises/02-restaurant-bill/src/restaurantBill.js
> +const restaurantBill = (cuenta) => {
hecho

2021-04-15 20:31 UTC, luucamay commented on 05-prework-exercises/02-restaurant-bill/README.md
> +## Estructura de la función `restaurantBill`
si mejor

2021-04-15 20:31 UTC, luucamay commented on 05-prework-exercises/01-coin-convert/README.md
> +## Estructura de la función `coinConvert`
al comienzo estara

2021-04-15 20:47 UTC, closed without merging