Basics html
Laboratoria/preseleccion-labs pull request #9
Opened 2021-04-08 20:18 UTC by moniyama

2021-04-20 21:08 UTC, merunga requested changes

2021-04-20 21:08 UTC, merunga commented on 02-basics/01-html/README.md
> +- Tipo: `lectura`
```suggestion
- Tipo: `practice`
```

2021-04-20 21:08 UTC, merunga commented on 02-basics/01-html/README.md
> +{% spoiler %}
```suggestion

```
quitaría el _spoiler_ para que no esté oculto

2021-04-20 21:08 UTC, merunga commented on 02-basics/01-html/README.md
> +{% endspoiler %}
```suggestion

```

2021-04-20 21:08 UTC, merunga commented on 02-basics/01-html/README.md
> +{% spoiler %}
Lo mismo q arriba, habria q probar si se pueden poner _quotes_ del tipo:
> En la etiqueta de `head` es donde contiene la información sobre la página,
  llamadas de *metadatos*.
  El elemento `meta` no hay etiqueta de cierre y representa [metadatos](https://developer.mozilla.org/es/docs/Glossary/Metadata)
  El elemento `title` define el título del documento que se muestra
en la barra de título del navegador o en la pestaña de una página

2021-04-20 21:08 UTC, merunga commented on 02-basics/01-html/README.md
> +El código al final deve estar parecido con eso:
```suggestion
El código al final debe estar parecido con eso:
```

2021-04-20 21:08 UTC, merunga commented on 02-basics/01-html/README.md
> +Darse cuenta de que ese mismo código sin indentación es muy más dificil de leer y entender:
```suggestion
Fíjate que ese mismo código sin indentación es muy más dificil de leer y entender:
```

2021-04-20 21:08 UTC, merunga commented on 02-basics/01-html/README.md
> +Los _comentarios_ permitem dejar notas sobre su código, su funcionalidad o indicar
```suggestion
Los _comentarios_ permiten dejar notas sobre su código, su funcionalidad o indicar
```

2021-04-20 21:08 UTC, merunga commented on 02-basics/01-html/README.md
> +los cambios necesarios para el futuro para las personas que leen o editan su código.
```suggestion
los cambios necesarios para el futuro, a las personas que leen o editan tu código.
```

2021-04-20 21:08 UTC, merunga commented on 02-basics/01-html/README.md
> +Hay 6 niveles `h1` hasta `h6`, sendo `h1` el nivel de sección más alto o más importante.
```suggestion
Hay 6 niveles `h1` hasta `h6`, siendo `h1` el nivel de sección más alto o más importante.
```

2021-04-20 21:08 UTC, merunga commented on 02-basics/01-html/README.md
> +pero recuerde que todo lo que desea que se muestre en su página web
```suggestion
pero recuerda que todo lo que quieres que se muestre en su página web
```

2021-04-20 21:08 UTC, merunga commented on 02-basics/01-html/README.md
> +Si escribe un párrafo, es posible que desee formatear una palabra o una frase, por ejemplo:
```suggestion
Si escribe un párrafo, es posible que desee darle formato una palabra o una frase, por ejemplo:
```

2021-04-20 21:08 UTC, merunga commented on 02-basics/01-html/README.md
> +Una forma de poner cualquier texto en negrito o cursivo es utilizando
```suggestion
Una forma de poner cualquier texto en negrita o cursiva es utilizando
```

2021-04-20 21:08 UTC, merunga commented on 02-basics/01-html/README.md
> +Testea formatar palavras y párrafos.
```suggestion
Testea formatear palabras y párrafos.
```

2021-04-20 21:08 UTC, merunga commented on 02-basics/01-html/README.md
> +Rero recuerde que todo lo que desea que se muestre en su página web
```suggestion
Pero recuerda que todo lo que deseas que se muestre en su página web
```

2021-04-20 21:08 UTC, merunga commented on 02-basics/01-html/README.md
> +es envuelto en comillas, seguiendo esa estructura:
```suggestion
está envuelto en comillas, seguiendo esta estructura:
```

2021-04-23 18:11 UTC, moniyama commented on 02-basics/01-html/README.md
> +{% spoiler %}
cambié ese spoiler por blockquote.. commit https://github.com/Laboratoria/preseleccion-labs/pull/9/commits/94565d8012bffc96bbfd65cd858fe5161f9c3048

2021-04-28 19:37 UTC, merged